# logback debug log ?/????
debug: false

# ?????? ????? ?? ??? ????? ?? ??? ????.
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.mightytony.projectboard: debug
    org.springframework.web.servlet: debug
    # JPA ?? ?? ??? ????? ????? (?) ?? ????? ? ????? ???? ? ? ???.
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: tony
    password: password1234!@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    # ???? ???? ?? ? ???
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true # ?? ???
      hibernate.default_batch_fetch_size: 100 # JPA
    #open-in-view: false
  h2:
    console:
      enabled: false
  sql:
    init:
      mode: always

#  thymeleaf:
#    cache: false

#  data:
#    rest:
#      base-path: /api
#      detection-strategy: annotated

---

spring:
  #profiles.active
  config.activate.on-profile: testdb
#  datasource:
#    url: jdbc:h2:mem:board;mode=mysql
#    driver-class-name: org.h2.Driver
#  sql.init.mode: always
#  test.database.replace: none
